
[build]
  command = "npm run build"
  publish = "dist"

# Define environment variables if needed
[build.environment]
  NODE_VERSION = "18"

# This ensures that React Router works correctly
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
